DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS gig;
DROP TABLE IF EXISTS worker;

CREATE TABLE client (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT  NOT NULL,
  oauth TEXT NOT NULL
);


CREATE TABLE gig (
  gid INTEGER PRIMARY KEY AUTOINCREMENT,
  cid INTEGER NOT NULL,
  wid INTEGER NOT NULL,
  submitted_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timeout_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  accepted_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status INTEGER NOT NULL,
  location TEXT NOT NULL,
  price INTEGER NOT NULL,
  FOREIGN KEY (cid) REFERENCES client (id),
  FOREIGN KEY (wid) REFERENCES worker (id)
);

CREATE TABLE worker (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);